version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: ./task-management
    container_name: task-management
    command: /bin/sh -c "rm -f /task-management/tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    volumes:
      - ./task-management:/task-management
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
