default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: task_management_development

test:
  <<: *default
  database: task_management_test

production:
  <<: *default
  database: task_management_production
  username: task_management
  password: <%= ENV['TASK_MANAGEMENT_DATABASE_PASSWORD'] %>
